### ISSUE TITLE
Controle de Alterações

### ISSUE THREAD

**Issue by BiancaFSilva** [ProjetoJobei/Jobei#2]
**Diário de Bordo**
- [x] Apresentação da equipe e do projeto
- [x] Diagrama de caso de uso
- [x] Concorrentes
- [x] Definir ODSs
- [x] Atualização semanal do que foi realizado

**Documentação**
- [x] Introdução
- [x] Imersão
  - [x] Caderno de sensibilidade
  - [x] Gráficos da pesquisa de campo
- [x] Analise e sintese
  - [x] Diagrama de afinidades
  - [x] Criação da persona
  - [x] Deinição do segmento de mercado
  - [x] Mapa de empatia
  - [x] Jornada do usuário
- [x] Ideação
  - [x] Mapa de atores
  - [x] Golden circle
- [x] Aspectos estratégicos
- [x] Protótipo
  - [x] Mapa do site
  - [x] Caso de uso
  - [x] Modelagem do banco de dados
  - [x] Telas
- [x] Planejamento financeiro
- [x] Termos de uso 
- [x] Política de Privacidade

**Site e Hospedagem**
- [x] Logo
- [x] Paleta de cores
- [x] Templates
- [x] Telas de cadastro
- [x] Telas de administração
- [x] Conexões com banco de dados
- [x] Conteúdo

**Pesquisa de Campo**
- [x] Divulgar
- [x] Tabulação das pesquisas
- [x] Entrevistas

**Redes sociais**
- [x] Email
- [x] Site próprio
- [x] Instagram
- [x] Facebook
- [x] Twitter

**Comment by ProjetoJobei** [comment]
Apresentação do Projeto: <br><b>02 de Dezembro de 2021</b>

**Comment by BiancaFSilva** [comment]
Concluído e carregado no issue destinado à Documentação ( #4 )
